package miyo
var lexiconEntries = []LexiconEntry{
	{Key: "AAC", Tag: TagAudioTerm, Canonical: "AAC"},
	{Key: "AAC2.0", Tag: TagAudioTerm, Canonical: "AAC"},
	{Key: "AC3", Tag: TagAudioTerm, Canonical: "AC3"},
	{Key: "DDP", Tag: TagAudioTerm, Canonical: "DDP"},
	{Key: "DDP2.0", Tag: TagAudioTerm, Canonical: "DDP"},
	{Key: "DDP5.1", Tag: TagAudioTerm, Canonical: "DDP"},
	{Key: "DD", Tag: TagAudioTerm, Canonical: "DD"},
	{Key: "DD2.0", Tag: TagAudioTerm, Canonical: "DD"},
	{Key: "DD5.1", Tag: TagAudioTerm, Canonical: "DD"},
	{Key: "EAC3", Tag: TagAudioTerm, Canonical: "EAC3"},
	{Key: "E-AC-3", Tag: TagAudioTerm, Canonical: "E-AC-3"},
	{Key: "FLAC", Tag: TagAudioTerm, Canonical: "FLAC"},
	{Key: "FLAC2.0", Tag: TagAudioTerm, Canonical: "FLAC"},
	{Key: "FLAC5.1", Tag: TagAudioTerm, Canonical: "FLAC"},
	{Key: "MP3", Tag: TagAudioTerm, Canonical: "MP3"},
	{Key: "Opus", Tag: TagAudioTerm, Canonical: "Opus", Ambiguous: true, Score: 1.5},
	{Key: "DTS", Tag: TagAudioTerm, Canonical: "DTS"},
	{Key: "DTS-HD", Tag: TagAudioTerm, Canonical: "DTS-HD"},
	{Key: "DTS-HD MA", Tag: TagAudioTerm, Canonical: "DTS-HD MA"},
	{Key: "TrueHD", Tag: TagAudioTerm, Canonical: "TrueHD"},
	{Key: "PCM", Tag: TagAudioTerm, Canonical: "PCM"},
	{Key: "LPCM", Tag: TagAudioTerm, Canonical: "LPCM"},
	{Key: "Dolby", Tag: TagAudioTerm, Canonical: "Dolby"},
	{Key: "Atmos", Tag: TagAudioTerm, Canonical: "Atmos"},
	{Key: "Dual Audio", Tag: TagAudioTerm, Canonical: "Dual Audio"},
	{Key: "DualAudio", Tag: TagAudioTerm, Canonical: "Dual Audio"},
	{Key: "Multi Audio", Tag: TagAudioTerm, Canonical: "Multi Audio"},

	{Key: "H264", Tag: TagVideoTerm, Canonical: "H.264"},
	{Key: "H.264", Tag: TagVideoTerm, Canonical: "H.264"},
	{Key: "H265", Tag: TagVideoTerm, Canonical: "H.265"},
	{Key: "H.265", Tag: TagVideoTerm, Canonical: "H.265"},
	{Key: "x264", Tag: TagVideoTerm, Canonical: "x264"},
	{Key: "x265", Tag: TagVideoTerm, Canonical: "x265"},
	{Key: "AVC", Tag: TagVideoTerm, Canonical: "AVC"},
	{Key: "HEVC", Tag: TagVideoTerm, Canonical: "HEVC"},
	{Key: "Xvid", Tag: TagVideoTerm, Canonical: "Xvid"},
	{Key: "AV1", Tag: TagVideoTerm, Canonical: "AV1"},
	{Key: "VP9", Tag: TagVideoTerm, Canonical: "VP9"},
	{Key: "MPEG2", Tag: TagVideoTerm, Canonical: "MPEG2"},
	{Key: "HDR", Tag: TagVideoTerm, Canonical: "HDR"},
	{Key: "HDR10", Tag: TagVideoTerm, Canonical: "HDR10"},
	{Key: "8bit", Tag: TagVideoTerm, Canonical: "8bit"},
	{Key: "8-bit", Tag: TagVideoTerm, Canonical: "8-bit"},
	{Key: "10bit", Tag: TagVideoTerm, Canonical: "10bit"},
	{Key: "10bits", Tag: TagVideoTerm, Canonical: "10bits"},
	{Key: "10-bit", Tag: TagVideoTerm, Canonical: "10-bit"},
	{Key: "Hi10P", Tag: TagVideoTerm, Canonical: "Hi10P"},

	{Key: "BD", Tag: TagSource, Canonical: "BD"},
	{Key: "BDISO", Tag: TagSource, Canonical: "BDISO"},
	{Key: "BDMV", Tag: TagSource, Canonical: "BDMV"},
	{Key: "JPBD", Tag: TagSource, Canonical: "BD"},
	{Key: "LD", Tag: TagSource, Canonical: "LD"},
	{Key: "LaserDisc", Tag: TagSource, Canonical: "LaserDisc"},
	{Key: "Laserdisc", Tag: TagSource, Canonical: "LaserDisc"},
	{Key: "BluRay", Tag: TagSource, Canonical: "Blu-Ray"},
	{Key: "Blu-ray", Tag: TagSource, Canonical: "Blu-ray"},
	{Key: "BDRip", Tag: TagSource, Canonical: "BDRip"},
	{Key: "DVD", Tag: TagSource, Canonical: "DVD"},
	{Key: "DVDISO", Tag: TagSource, Canonical: "DVDISO"},
	{Key: "DVD-Rip", Tag: TagSource, Canonical: "DVD-Rip"},
	{Key: "WEB", Tag: TagSource, Canonical: "WEB"},
	{Key: "WEB-DL", Tag: TagSource, Canonical: "WEB-DL"},
	{Key: "WEBDL", Tag: TagSource, Canonical: "WEB-DL"},
	{Key: "WEBRip", Tag: TagSource, Canonical: "WEBRip"},
	{Key: "HDTV", Tag: TagSource, Canonical: "HDTV"},
	{Key: "TV", Tag: TagSource, Canonical: "TV", Ambiguous: true, Score: 1.5},
	{Key: "ТВ", Tag: TagSource, Canonical: "TV", Ambiguous: true, Score: 1.5},
	{Key: "CR", Tag: TagSource, Canonical: "CR"},
	{Key: "AMZN", Tag: TagSource, Canonical: "AMZN"},
	{Key: "NF", Tag: TagSource, Canonical: "NF"},
	{Key: "ADN", Tag: TagSource, Canonical: "ADN"},
	{Key: "ABEMA", Tag: TagSource, Canonical: "ABEMA"},
	{Key: "Baha", Tag: TagSource, Canonical: "Baha"},
	{Key: "BILI", Tag: TagSource, Canonical: "BILI"},
	{Key: "DSNP", Tag: TagSource, Canonical: "DSNP"},
	{Key: "HIDIVE", Tag: TagSource, Canonical: "HIDIVE"},
	{Key: "HIDI", Tag: TagSource, Canonical: "HIDI"},
	{Key: "HULU", Tag: TagSource, Canonical: "HULU"},
	{Key: "TVER", Tag: TagSource, Canonical: "TVER"},
	{Key: "YTB", Tag: TagSource, Canonical: "YTB"},
	{Key: "U-NEXT", Tag: TagSource, Canonical: "U-NEXT"},
	{Key: "AT-X", Tag: TagSource, Canonical: "AT-X"},
	{Key: "iQ", Tag: TagSource, Canonical: "iQ", Ambiguous: true, Score: 1.5},
	{Key: "iQIYI", Tag: TagSource, Canonical: "iQIYI"},
	{Key: "ANIPLUS", Tag: TagSource, Canonical: "ANIPLUS", Ambiguous: true, Score: 1.5},
	{Key: "BS11", Tag: TagSource, Canonical: "BS11", Ambiguous: true, Score: 1.5},
	{Key: "BS-EX", Tag: TagSource, Canonical: "BS-EX", Ambiguous: true, Score: 1.5},
	{Key: "BS-FUJI", Tag: TagSource, Canonical: "BS-FUJI", Ambiguous: true, Score: 1.5},
	{Key: "BS-TX", Tag: TagSource, Canonical: "BS-TX", Ambiguous: true, Score: 1.5},
	{Key: "BS-TBS", Tag: TagSource, Canonical: "BS-TBS", Ambiguous: true, Score: 1.5},
	{Key: "BS-NTV", Tag: TagSource, Canonical: "BS-NTV", Ambiguous: true, Score: 1.5},
	{Key: "BS-ANIMAX", Tag: TagSource, Canonical: "BS-ANIMAX", Ambiguous: true, Score: 1.5},
	{Key: "BSN", Tag: TagSource, Canonical: "BSN", Ambiguous: true, Score: 1.5},
	{Key: "CS-EX2", Tag: TagSource, Canonical: "CS-EX2", Ambiguous: true, Score: 1.5},
	{Key: "KIDS", Tag: TagSource, Canonical: "KIDS", Ambiguous: true, Score: 1.5},
	{Key: "OVEIL", Tag: TagSource, Canonical: "OVEIL", Ambiguous: true, Score: 1.5},
	{Key: "AS", Tag: TagSource, Canonical: "AS", Ambiguous: true, Score: 1.5},

	{Key: "ENG", Tag: TagLanguage, Canonical: "Eng"},
	{Key: "English", Tag: TagLanguage, Canonical: "English"},
	{Key: "JPN", Tag: TagLanguage, Canonical: "Jpn"},
	{Key: "JP", Tag: TagLanguage, Canonical: "jp", Ambiguous: true, Score: 1.5},
	{Key: "JAP", Tag: TagLanguage, Canonical: "Jap"},
	{Key: "Japanese", Tag: TagLanguage, Canonical: "Japanese"},
	{Key: "SUBFRENCH", Tag: TagLanguage, Canonical: "SUBFRENCH"},
	{Key: "VF", Tag: TagLanguage, Canonical: "VF", Ambiguous: true, Score: 1.5},
	{Key: "CHT", Tag: TagLanguage, Canonical: "CHT"},
	{Key: "CHS", Tag: TagLanguage, Canonical: "CHS"},
	{Key: "RU", Tag: TagLanguage, Canonical: "ru", Ambiguous: true, Score: 1.5},
	{Key: "RUS", Tag: TagLanguage, Canonical: "RUS"},
	{Key: "VOSTFR", Tag: TagLanguage, Canonical: "VOSTFR"},
	{Key: "FR", Tag: TagLanguage, Canonical: "FR", Ambiguous: true, Score: 1.5},
	{Key: "PT-BR", Tag: TagLanguage, Canonical: "PT-BR"},
	{Key: "Spanish", Tag: TagLanguage, Canonical: "Spanish"},
	{Key: "Español", Tag: TagLanguage, Canonical: "Spanish"},
	{Key: "Espanol", Tag: TagLanguage, Canonical: "Spanish"},
	{Key: "Latino", Tag: TagLanguage, Canonical: "Spanish"},
	{Key: "ESP", Tag: TagLanguage, Canonical: "ESP", Ambiguous: true, Score: 1.5},
	{Key: "ITA", Tag: TagLanguage, Canonical: "ITA", Ambiguous: true, Score: 1.5},

	{Key: "Sub", Tag: TagSubtitles, Canonical: "Sub"},
	{Key: "Subs", Tag: TagSubtitles, Canonical: "Subs"},
	{Key: "MultiSub", Tag: TagSubtitles, Canonical: "MultiSub"},
	{Key: "MultiSubtitles", Tag: TagSubtitles, Canonical: "MultiSubtitles"},
	{Key: "Multi Subs", Tag: TagSubtitles, Canonical: "Multi-Subs"},
	{Key: "M-SUB", Tag: TagSubtitles, Canonical: "M-SUB"},
	{Key: "English-Sub", Tag: TagSubtitles, Canonical: "English-Sub"},
	{Key: "English Sub", Tag: TagSubtitles, Canonical: "English-Sub"},
	{Key: "English-Subs", Tag: TagSubtitles, Canonical: "English-Subs"},
	{Key: "Eng-Sub", Tag: TagSubtitles, Canonical: "Eng-Sub"},
	{Key: "Eng Sub", Tag: TagSubtitles, Canonical: "Eng-Sub"},
	{Key: "Eng-Subs", Tag: TagSubtitles, Canonical: "Eng-Subs"},
	{Key: "Dub", Tag: TagAudioTerm, Canonical: "Dub"},
	{Key: "Dubbed", Tag: TagAudioTerm, Canonical: "Dubbed"},
	{Key: "Soft Sub", Tag: TagSubtitles, Canonical: "Soft Sub"},
	{Key: "Soft Subs", Tag: TagSubtitles, Canonical: "Soft Subs"},
	{Key: "SoftSub", Tag: TagSubtitles, Canonical: "SoftSub"},
	{Key: "SoftSubs", Tag: TagSubtitles, Canonical: "SoftSubs"},
	{Key: "HardSub", Tag: TagSubtitles, Canonical: "HardSub"},
	{Key: "HardSubs", Tag: TagSubtitles, Canonical: "HardSubs"},

	{Key: "Batch", Tag: TagReleaseInformation, Canonical: "Batch"},
	{Key: "Complete", Tag: TagReleaseInformation, Canonical: "Complete"},
	{Key: "REPACK", Tag: TagReleaseInformation, Canonical: "REPACK"},
	{Key: "PROPER", Tag: TagReleaseInformation, Canonical: "PROPER"},
	{Key: "Remux", Tag: TagReleaseInformation, Canonical: "Remux"},
	{Key: "Remaster", Tag: TagReleaseInformation, Canonical: "Remaster"},
	{Key: "Remastered", Tag: TagReleaseInformation, Canonical: "Remastered"},
	{Key: "CUSTOM", Tag: TagReleaseInformation, Canonical: "CUSTOM"},
	{Key: "READNFO", Tag: TagReleaseInformation, Canonical: "READNFO"},
	{Key: "Uncensored", Tag: TagReleaseInformation, Canonical: "Uncensored"},
	{Key: "Uncut", Tag: TagReleaseInformation, Canonical: "Uncut"},
	{Key: "Final", Tag: TagReleaseInformation, Canonical: "Final", Ambiguous: true, Score: 1.5},

	{Key: "Movie", Tag: TagAnimeType, Canonical: "Movie", Ambiguous: true, Score: 1.8},
	{Key: "Movies", Tag: TagAnimeType, Canonical: "Movies"},
	{Key: "OP", Tag: TagAnimeType, Canonical: "OP", Ambiguous: true, Score: 1.8},
	{Key: "ED", Tag: TagAnimeType, Canonical: "ED", Ambiguous: true, Score: 1.8},
	{Key: "NCOP", Tag: TagAnimeType, Canonical: "NCOP"},
	{Key: "NCOPs", Tag: TagAnimeType, Canonical: "NCOPs"},
	{Key: "NCED", Tag: TagAnimeType, Canonical: "NCED"},
	{Key: "NCEDs", Tag: TagAnimeType, Canonical: "NCEDs"},
	{Key: "SP", Tag: TagAnimeType, Canonical: "SP", Ambiguous: true, Score: 1.8},
	{Key: "Special", Tag: TagAnimeType, Canonical: "Special", Ambiguous: true, Score: 1.8},
	{Key: "Specials", Tag: TagAnimeType, Canonical: "Specials"},
	{Key: "TV Series", Tag: TagAnimeType, Canonical: "TV Series", Ambiguous: true, Score: 1.8},
	{Key: "OVA", Tag: TagAnimeType, Canonical: "OVA"},
	{Key: "OVAs", Tag: TagAnimeType, Canonical: "OVAs"},
	{Key: "OAV", Tag: TagAnimeType, Canonical: "OAV"},
	{Key: "ONA", Tag: TagAnimeType, Canonical: "ONA"},
	{Key: "OAD", Tag: TagAnimeType, Canonical: "OAD"},

	{Key: "Android", Tag: TagDeviceCompatibility, Canonical: "Android", Ambiguous: true, Score: 1.5},
	{Key: "iPad", Tag: TagDeviceCompatibility, Canonical: "iPad"},
	{Key: "iPhone", Tag: TagDeviceCompatibility, Canonical: "iPhone"},
	{Key: "iPod", Tag: TagDeviceCompatibility, Canonical: "iPod"},
	{Key: "PS3", Tag: TagDeviceCompatibility, Canonical: "PS3"},
	{Key: "Xbox", Tag: TagDeviceCompatibility, Canonical: "Xbox"},

	// CJK Language, Subtitle and Release Info tags
	{Key: "GB_CN", Tag: TagLanguage, Canonical: "CHS"},
	{Key: "GB_JP", Tag: TagLanguage, Canonical: "CHS/JPN"},
	{Key: "GB", Tag: TagLanguage, Canonical: "CHS", Ambiguous: true, Score: 1.5},
	{Key: "繁体", Tag: TagLanguage, Canonical: "CHT"},
	{Key: "繁體", Tag: TagLanguage, Canonical: "CHT"},
	{Key: "简体", Tag: TagLanguage, Canonical: "CHS"},
	{Key: "簡體", Tag: TagLanguage, Canonical: "CHS"},
	{Key: "繁体内嵌", Tag: TagSubtitles, Canonical: "CHT"},
	{Key: "繁體內嵌", Tag: TagSubtitles, Canonical: "CHT"},
	{Key: "简体内嵌", Tag: TagSubtitles, Canonical: "CHS"},
	{Key: "簡體內嵌", Tag: TagSubtitles, Canonical: "CHS"},
	{Key: "简繁内封字幕", Tag: TagSubtitles, Canonical: "CHS/CHT"},
	{Key: "简繁日内封字幕", Tag: TagSubtitles, Canonical: "CHS/CHT/JPN"},
	{Key: "简繁日内封", Tag: TagSubtitles, Canonical: "CHS/CHT/JPN"},
	{Key: "簡繁內封字幕", Tag: TagSubtitles, Canonical: "CHS/CHT"},
	{Key: "簡繁日內封字幕", Tag: TagSubtitles, Canonical: "CHS/CHT/JPN"},
	{Key: "簡繁日內封", Tag: TagSubtitles, Canonical: "CHS/CHT/JPN"},
	{Key: "简繁内封", Tag: TagSubtitles, Canonical: "CHS/CHT"},
	{Key: "簡繁內封", Tag: TagSubtitles, Canonical: "CHS/CHT"},
	{Key: "繁日雙語", Tag: TagSubtitles, Canonical: "CHT/JPN"},
	{Key: "繁日双语", Tag: TagSubtitles, Canonical: "CHT/JPN"},
	{Key: "简日双语", Tag: TagSubtitles, Canonical: "CHS/JPN"},
	{Key: "简日雙語", Tag: TagSubtitles, Canonical: "CHS/JPN"},
	{Key: "雙語", Tag: TagAudioTerm, Canonical: "Dual Audio"},
	{Key: "双语", Tag: TagAudioTerm, Canonical: "Dual Audio"},
	{Key: "繁日", Tag: TagSubtitles, Canonical: "CHT/JPN"},
	{Key: "简日", Tag: TagSubtitles, Canonical: "CHS/JPN"},
	{Key: "国语", Tag: TagLanguage, Canonical: "Chinese"},
	{Key: "國語", Tag: TagLanguage, Canonical: "Chinese"},
	{Key: "粤语", Tag: TagLanguage, Canonical: "Cantonese"},
	{Key: "粵語", Tag: TagLanguage, Canonical: "Cantonese"},
	{Key: "无修", Tag: TagReleaseInformation, Canonical: "Uncensored"},
	{Key: "无修版", Tag: TagReleaseInformation, Canonical: "Uncensored"},
	{Key: "年齡限制版", Tag: TagReleaseInformation, Canonical: "Uncensored"},
	{Key: "合集", Tag: TagReleaseInformation, Canonical: "Batch"},

	// Dub/language labels commonly embedded in CJK filenames
	{Key: "中文配音", Tag: TagAudioTerm, Canonical: "Chinese Dub"},
	{Key: "台配", Tag: TagAudioTerm, Canonical: "Taiwanese Dub"},
	{Key: "中配", Tag: TagAudioTerm, Canonical: "Chinese Dub"},
	{Key: "国配", Tag: TagAudioTerm, Canonical: "Chinese Dub"},
	{Key: "國配", Tag: TagAudioTerm, Canonical: "Chinese Dub"},
	{Key: "日語", Tag: TagLanguage, Canonical: "JPN"},
	{Key: "日语", Tag: TagLanguage, Canonical: "JPN"},
	{Key: "中字", Tag: TagSubtitles, Canonical: "CHS"},
	{Key: "中文字幕", Tag: TagSubtitles, Canonical: "CHS"},
	{Key: "繁中", Tag: TagSubtitles, Canonical: "CHT"},
	{Key: "简中", Tag: TagSubtitles, Canonical: "CHS"},

	// RAW release indicator
	{Key: "RAW", Tag: TagLanguage, Canonical: "RAW"},
}
